apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: app-wil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-wil
  template:
    metadata:
      labels:
        app: app-wil
    spec:
      containers:
      - name: guestbook
        image: "gcr.io/heptio-images/ks-guestbook-demo:0.1"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-wil
  namespace: dev
spec:
  type: ClusterIp
  ports:
  - port: 8888
    targetPort: 80
  selector:
    app: app-wil
